export const theme = {
    dark: "#1F1F24",
    black: "#050505",
    textColor: "orange",
    hrdark: "2px solid #050505",
    hrblack: "2px solid #1F1F24",
    button: "linear-gradient(45deg, #ff4e55, orange)",
    btnText: "#ffffff",
    input: "transparent",
    border: "2px solid #b02a2e",
    spinnerBorderLine: "4px solid #1F1F24",
    loaderBorder: "orange",
    scrollTrack: "#050505",
    scrollThumb: "orange",
};